all:
	xcodebuild -target XiphQT -configuration Release

debug:
	xcodebuild -target XiphQT -configuration Debug

decoders:
	xcodebuild -target 'XiphQT (decoders)' -configuration Release

clean:
	xcodebuild -target XiphQT -configuration Release clean
